### ISSUE TITLE
Allow public talk submissions

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#252]
As requestted by Debconf people, so we don't lose track of it
- Expose all talk submissions, rather than just those accepted
  - Should this be totally public, or just to logged-in users?
  - Just logged in users reduces some of the spam concerns, but may not fit Debconf's requirements.
  - Do we need to restrict publishing by talk type?
- Possibly some sort of talk voting scheme?
  - Build this on top of the KeyValue stuff?

**Comment by shirishag75** [comment]
As an interested person, I would suggest having some sort of privacy flip-flop built-in and letting the speakers/proposal makers/talk submitter also decide. Many a time people title their talk mysteriously and are gladly surprised. Having all the content before-hand would ruin the surprise for many, including myself (putting the attendee hat on) .

**Comment by stefanor** [comment]
> Possibly some sort of talk voting scheme? 

Implemented in #418.

**Comment by stefanor** [comment]
With some more thought, I think a useful refinement of this is:

There should be some talk types that are inherently public: e.g. BoF, ad-hoc session, open space submission. This can be a flag on the talk type.

There are spam concerns here, because it's making user-provided content public on the site. Events get spammy talk submissions (and user bios). So a useful additional feature here would be a "report content" button on any page with user-defined content. Obviously this can be a follow-up.
