### ISSUE TITLE
Django 2.2 LTS Support

### ISSUE THREAD

**Issue by theastroventure** [CTPUG/wafer#489]
Are there any plans to support Django 2.2 LTS in the near future?

When I initially installed wafer, it defaulted to Django 2.2, and I see that the first issue with supporting 2.2 is with Markitup, which seems to be unsupported. Since Django 2.0 is no longer supported and 1.11 will be unsupported in April 2020, I am trying to decide which version of Django to use if I start to use wafer soon. Thanks.

**Comment by hodgestar** [comment]
We do plan to support Django 2.2, but we'd need to either get a patch and new release to django-markitup first, or fork that and do the same ourselves. :/

**Comment by programmylife** [comment]
Thank you for the update. I am helping to set up the website for SciPy for next summer and we would like to adopt wafer, but we are concerned about starting with 1.11 since it will be EOL by the time the conference comes around.

I have posted to the pull request made by @stefanor (https://github.com/zsiciarz/django-markitup/pull/21) to see if we can hopefully get the owner of django-markitup to merge the PR (I see you did over the summer as well). In the meantime, I was considering using a fork of that repo to install it.

@stefanor , I noticed you created this fork: https://github.com/stefanor/django-markitup/tree/django2.0 Have you used that successfully with a new project with wafer on 2.2 or 2.0?

**Comment by programmylife** [comment]
Have you considered swapping markitup with https://github.com/jamesturk/django-markupfield ? I was looking through the issue and PR on markitup and found this project https://github.com/WimpyAnalytics/django-andablog that made that swap to move to Django 2.2.

**Comment by drnlm** [comment]
Closing this, since we officially support Django 2.2 since the 0.8.1 release (Django 3 support is in progress).
