### ISSUE TITLE
Budget functionality

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#98]
Mentioned in discussions around PyCon ZA 2015 as a possibly useful future enhancement:

At minimum, should handle basic lists of expenses and income, and provide some nice formatting for helping keep everything on track.

Issues around suitable access permissions and such need to be resolved.

Items probably need due / expected dates as well.

**Comment by madduck** [comment]
If I am allowed a comment: this is going to be over the top and won't satisfy everyone's needs anyway. I'd rather suggest using Odoo (open community branch) for this and figuring out a way to link the databases…

Or just keep the accounting/budgeting separate. It's *way* too complex, IMHO, especially since I don't see Wafer as a payment processor anyway, so those data come from elsewhere anyway. For instance, you've used Quicket in such a way that Wafer didn't even need to know the price of the tickets… keep it simple.

**Comment by drnlm** [comment]
Arguably there are better tools for this, and having them in wafer isn't the right call.
